### ISSUE TITLE
Alternative Styles (CSS/HTML)

### ISSUE THREAD

**Issue by Sazu-bit** [EdwinRodger/MyMangaDataBase#2]
### Describe your suggested feature

I'd like to see MyMangaDataBase get an update to its style. When I opened up the demo I saw a rather clunky looking table. I would like to use MyMangaDataBase, but the design is putting me off. 

The most common design is to avoid blatant table layouts and instead use 'cards', which are easier to consume. I have no clue how to implement this with the tools you have available... but divs are really useful. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by EdwinRodger** [comment]
Completed in 283d69a85b139d268e9eced4f6497b3f5faaf64e
The card layout will be something like this https://getbootstrap.com/docs/5.3/components/card/#horizontal
Also the demo website is outdated and I will update it in near future
