### ISSUE TITLE
Anilist and MangaUpdate Import Support

### ISSUE THREAD

**Issue by LadyHaywood** [EdwinRodger/MyMangaDataBase#4]
### Describe your suggested feature

Allowing import list from anilist and mangaupdates.
Mostly mangaupdates since it seems like they have more entries than anilist and mal.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by EdwinRodger** [comment]
Thanks for the suggestion. The requested feature of 

- AniList (ff5cc112698135078adbe9f52baf8155e96449fd, be201e665cc1abdfc6369d3d54cedff8cbdec276) and
- MangaUpdates (e598e638c808db1eb66f1cf997108fa8933eb22b)

will be available to use in next release
