### ISSUE TITLE
End Date field is emptied when going to edit if it was set to 01/01/0001 instead of keeping 01/01/0001

### ISSUE THREAD

**Issue by Kazer67** [EdwinRodger/MyMangaDataBase#9]
### Steps to reproduce

Add or Edit a Manga with no End Date (so End Date at 01/01/0001).
Save the change.
Go back to the Manga list and then go back to said Manga.

[EndDate_Empty.webm](https://github.com/EdwinRodger/MyMangaDataBase/assets/45577220/e0de674e-9f04-4794-8118-5cd968073a24)

### Expected behavior

Going to Edit on a Manga with no end date should default to 01/01/0001

### Actual behavior

The 01/01/0001 No End Date isn't saved.

### MyMangaDataBase version

2.4.0

### Other details

The issue doesn't exist when there's an actual End Date specified.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the lastest version.
- [X] I will fill out all of the requested information in this form.

**Comment by EdwinRodger** [comment]
Fixed in 84e9a13c67fbfaed633c2a9d320600f7c82b6638
Also, the date field is always `dd-mm-yyyy` in linux for some reason.

Another thing, this is Linux specific error, couldn't able to reproduce on Windows.

**Comment by Kazer67** [comment]
Work great.

Maybe also make the End Date not required when adding a new manga would be a good idea.

**Comment by Kazer67** [comment]
Work great.

Seem like it should also be added to the "Add Manga" as I was able to add a new manga without End Date but I can't edit it now after adding it (I'm getting an Error 500)

**Comment by EdwinRodger** [comment]
Fixed here 2837d3af253885d7d0ff5ab684582fa12a182fec

Apparently, in Linux, if date is set to 0001-01-01, it always returns as `None`
Whereas in windows, the date 0001-01-01 is always return as `"0001-01-01"`

**Comment by Kazer67** [comment]
Can confirm, it work now.

(I also fixed the issue directly in the SQLite database for the one who had NONE at END-DATE).
